# Generated by Django 4.2 on 2023-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=255)),
                ('airline', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('stoppage', models.CharField(choices=[('nostoppage', 'Nostoppage'), ('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='nostoppage', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
