# Generated by Django 4.2 on 2023-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='predicted_price',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='stoppage',
            field=models.CharField(choices=[('nostoppage', 'Nostoppage'), ('one', '1 Stop'), ('two', '2 Stop'), ('three', '3 Stop')], default='nostoppage', max_length=100),
        ),
    ]
