# Generated by Django 4.2.1 on 2023-06-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_predicted_price_alter_flight_stoppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(choices=[('select', 'Select Airline'), ('jetairways', 'Jet Airways'), ('indigo', 'IndiGo'), ('airindia', 'Air India'), ('multiplecarriers', 'Multiple carriers'), ('spicejet', 'SpiceJet'), ('vistara', 'Vistara'), ('airasia', 'Air Asia'), ('goair', 'GoAir'), ('multiplecarrierspremiumeconomy', 'Multiple carriers Premium economy'), ('jetairwaysbusiness', 'Jet Airways Business'), ('vistarapremiumeconomy', 'Vistara Premium economy'), ('trujet', 'Trujet')], default='select', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('select', 'Select City'), ('delhi', 'Delhi'), ('bangalore', 'Bangalore'), ('newdelhi', 'New Delhi'), ('kolkata', 'Kolkata'), ('mumbai', 'Mumbai'), ('cochin', 'Cochin'), ('chennai', 'Chennai'), ('hyderabad', 'Hyderabad')], default='select', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.CharField(choices=[('select', 'Select City'), ('delhi', 'Delhi'), ('bangalore', 'Bangalore'), ('newdelhi', 'New Delhi'), ('kolkata', 'Kolkata'), ('mumbai', 'Mumbai'), ('cochin', 'Cochin'), ('chennai', 'Chennai'), ('hyderabad', 'Hyderabad')], default='select', max_length=255),
        ),
    ]
