# Generated by Django 4.2.1 on 2023-06-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_airline_alter_flight_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='stoppage',
            field=models.CharField(choices=[('0', 'Nostoppage'), ('1', '1 Stop'), ('2', '2 Stop'), ('3', '3 Stop')], default='0', max_length=100),
        ),
    ]
