# Generated by Django 4.2.1 on 2023-07-22 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotel_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotelimages', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
