# Generated by Django 4.2.1 on 2023-07-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amnities',
            name='amenity',
            field=models.CharField(choices=[('Room Service', 'Room Service'), ('Parking', 'Parking'), ('Wifi', 'Wifi'), ('Swimming Pool', 'Swimming Pool'), ('Gym', 'Gym'), ('Spa', 'Spa'), ('Garden', 'Garden'), ("Children's Play Area", "Children's Play Area"), ('Bar', 'Bar')], max_length=255),
        ),
    ]
