# Generated by Django 4.2 on 2023-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(choices=[(True, 'Booked'), (False, 'Cancelled')], default=True),
        ),
    ]
